[package]
name = "opticon-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["ws"] }
tokio = { version = "1.53.1", features = ["full"] }
futures-util = "=0.3.32"
tower-http = { version = "0.7.0", features = ["fs"] }
axum-server = { version = "0.8.0", features = ["tls-rustls"] }
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite", "macros"] }
dotenvy = "0.15.7"
argon2 = { version = "0.5.3", features = ["std"] }
tower-sessions = "0.15.0"
serde = { version = "1.0.229", features = ["derive"] }
web-push = "0.11.0"
